site_name: Pho's ECM Rush Guide
theme:
  name: material
  favicon: favicon.png
  logo: ecm.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Toggle dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Toggle light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Toggle auto
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.fancylists
  - pymdownx.saneheaders

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

nav:
  - Creation Instruction: guide-creation-instructions.md
  - Intro: index.md
  - FAQ: faq.md
  - SSD:
    - ssd/index.md
    - Resources: ssd/resources.md
    - Role 1:
      - ssd/role-1/index.md
      - Diamond Store: ssd/role-1/diamond-store.md
      - Art Gallery: ssd/role-1/art-gallery.md
      - Sweepot: ssd/role-1/sweepot.md
      - Shadow Raid: ssd/role-1/shadow-raid.md
      - Nightclub: ssd/role-1/nightclub.md
    - Role 2:
      - ssd/role-2/index.md
      - Diamond Store: ssd/role-2/diamond-store.md
      - Art Gallery: ssd/role-2/art-gallery.md
      - Sweepot: ssd/role-2/sweepot.md
      - Shadow Raid: ssd/role-2/shadow-raid.md
      - Nightclub: ssd/role-2/nightclub.md
    - Role 3:
      - ssd/role-3/index.md
      - Diamond Store: ssd/role-3/diamond-store.md
      - Art Gallery: ssd/role-3/art-gallery.md
      - Sweepot: ssd/role-3/sweepot.md
      - Shadow Raid: ssd/role-3/shadow-raid.md
      - Nightclub: ssd/role-3/nightclub.md
  - NCDR:
    - ncdr/index.md
    - Resources: ncdr/resources.md
    - Role 1:
      - ncdr/role-1/index.md
      - Depot: ncdr/role-1/depot.md
      - Nightclub: ncdr/role-1/nightclub.md
      - Rush Hour: ncdr/role-1/rush-hour.md
    - Role 2:
      - ncdr/role-2/index.md
      - Depot: ncdr/role-2/depot.md
      - Nightclub: ncdr/role-2/nightclub.md
      - Rush Hour: ncdr/role-2/rush-hour.md
    - Role 3:
      - ncdr/role-3/index.md
      - Depot: ncdr/role-3/depot.md
      - Nightclub: ncdr/role-3/nightclub.md
      - Rush Hour: ncdr/role-3/rush-hour.md
